---
title: "Vulnerability Resets in Space Fortress"
classoption: landscape
output:
  pdf_document: default
  html_notebook: default
  html_document: default
---

***

## Reasons for a vlner reset:
+ Correct rule, wrong count (vlner==10)
+ 1b. Wrong rule, correct count (vlner==10)
+ Trying to shoot faster (vlner==*)
+ Doppler effect

```{r,include=FALSE}
setwd("/mnt/data/staircase/scripts")
require(data.table)
require(ggplot2)
require(RColorBrewer)
require(lme4)
require(lmerTest)

d = rbindlist(lapply(list.files("../data/processed_new/eeg_event_files_new",pattern="*reset-events.tsv",full.names=TRUE), fread, header=T))
d[,pnts:=ifelse(game<=10,points_total,points_total/2)]
d[,category:=factor(ifelse(vlner_old==10,"10",ifelse(vlner_old==1,"1","2-9")),levels=c("1","2-9","10"),ordered=TRUE)]
d[,sid:=factor(sid,levels=d[,.SD[1,pnts],by=c("game","sid")][order(sid,-V1),mean(.SD[1:10,V1]),by="sid"][order(-V1)][,sid],ordered=TRUE)]

d2=d[!is.infinite(nextShotLatency) & nextShotLatency!=-1,.(meanNextShotLatency=mean(nextShotLatency/34),pnts=.SD[1,pnts]),by=c("sid","game")]

dd = d[!is.infinite(nextShotLatency) & nextShotLatency!=-1,as.data.table(table(vlner_old)),by=c("sid")]
dd = merge(dd,d[!is.infinite(nextShotLatency) & nextShotLatency!=-1,.SD[1,total_shots],by=c("sid","game")][,.(total_shots=sum(V1)),by="sid"])
dd[,vlner_old:=factor(vlner_old,levels=1:10,ordered=T)]
dd[,category:=factor(ifelse(vlner_old==10,"10",ifelse(vlner_old==1,"1","2-9")),levels=c("1","2-9","10"),ordered=TRUE)]
```

## Ratio between resets at given VLNER and total shots

```{r,echo=FALSE,warning=FALSE,message=FALSE,fig.width=10.5,fig.height=4}
ggplot(dd) + 
  geom_bar(aes(y=N/total_shots,x=vlner_old,fill=category),stat="identity",width=.5) + 
  facet_wrap(~sid,nrow=2) + 
  scale_fill_manual("VLNER",values=c("blue","black","red")) +
  theme(legend.position="top") +
  ylab("Number of Resets / Total Number of Shots") +
  xlab("Vlner Before Reset")
```

## Shot latency post VLNER reset

```{r,echo=FALSE,warning=FALSE,message=FALSE,fig.width=10.5,fig.height=7.5}
ggplot(d[(nextShotLatency/34)<2 & nextShotLatency!=-1]) + 
  geom_hline(aes(yintercept=.250),color="magenta",linetype="dashed") +
  geom_point(aes(x=((game-1)*60000+game_time)/60000,y=nextShotLatency/34,color=category,shape=(nextHitLatency/34)<.250),size=.75) + 
  facet_wrap(~sid,nrow=2) + 
  scale_color_manual("VLNER at Shot",values=c("blue","black","red")) +
  scale_shape_manual("Shot Triggers Reset",values=c(1,3)) +
  theme(legend.position="top") + 
  xlab("Game") + ylab("Next Shot Latency (seconds)")
```